config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'private/uploads/:asset_type/:file', to: 'private_assets#show'

  root 'pages#index'
  resources :users do
    member do
      get :edit_password
      put :update_password
    end
  end
  resources :customers do
    resources :offices do
      resources :contacts, only: [:index]
      resources :phones
      resources :emails
      resources :sites
      resources :office_photos, path: 'photos'
      resources :addresses, except: [:index]
    end
  end
  resources :categories
  resources :countries do
    member do
      get :states
    end
  end
  resources :states do
    member do
      get :cities
    end
  end
  resources :cities do
    member do
      get :get_streets
    end
    resources :streets do
      member do
        get :get_houses
      end
      resources :houses
    end
    collection do
      get :states_in_country
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/office.rb
class Office < ActiveRecord::Base
  validates :name, :customer, presence: true
  validates :name, :uniqueness => { :case_sensitive => false }
  belongs_to :customer
  has_and_belongs_to_many :categories
  has_many :contacts, :dependent => :destroy
  has_many :office_photos, :dependent => :destroy
  has_one :address, :dependent => :destroy
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  load_and_authorize_resource
  before_action :set_customer
  before_action :set_office, only: [:show, :edit, :update, :destroy]

  # GET /offices
  # GET /offices.json
  def index
    @search = @customer.offices.search(params[:q])
    @offices = @search.result.page(params[:page])
    @photos_count = OfficePhoto.group(:office_id).count
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offices }
    end
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
    @search = @office.contacts.search(params[:q])
    @contacts = @search.result.page(params[:page])
  end

  # GET /offices/new
  def new
    @office = Office.new
    @categories = Category.all
  end

  # GET /offices/1/edit
  def edit
    @categories = Category.all
  end

  # POST /offices
  # POST /offices.json
  def create
    @categories = Category.all
    @office = @customer.offices.new(office_params)

    respond_to do |format|
      if @office.save

        format.html { redirect_to customer_offices_path(@customer), notice: t(:office_created) }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    @categories = Category.all
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to customer_offices_path(@customer), notice: t(:office_updated) }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to customer_offices_path(@customer), notice: t(:office_destroyed) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:customer_id])
    end

    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.require(:office).permit(:name, :desc, :category_ids => [])
    end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.slim
-content_for :javascripts do
  = javascript_include_tag 'offices'
-if @office.errors.any?
  .alert.alert-danger
    button type="button" class="close" data-dismiss="alert"
      | &times;
    h4=t('errors.title')
    ul
    - @office.errors.full_messages.each do |msg|
      li= msg
= form_for [@customer, @office], :html => { :class => "form-horizontal" } do |f|
  .form-group
    = f.label :name, t(:name), :class => 'control-label col-md-2'
    .col-sm-3
      = f.text_field :name, :class => 'text_field form-control'
  .form-group
    = f.label :desc, t(:desc), :class => 'control-label col-md-2'
    .col-sm-3
      = f.text_area :desc, :class => 'text_field form-control', rows: 6
  .form-group
    = f.label :category_ids, t(:categories)+':', class: "col-sm-2 control-label"
    .col-sm-3
      = f.select :category_ids, @categories.collect  {|p| [ p.name, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_categories), :multiple => true, :class => 'form-control'}
  .form-group
    .col-md-offset-2.col-sm-3
      =' f.button t(:save), :class =>'btn btn-primary', :disable_with => t(:please_wait)
      = link_to t(:cancel), customer_offices_path, :class => 'btn btn-default'

app/views/offices/edit.html.slim
div class="page-header"
  h1=t(:edit_office)
= render :partial => "form"

app/views/offices/index.html.slim
.page-header
  h1=t(:listing_offices)
p
  button.btn.btn-primary type="button" class="" data-toggle="collapse" data-target="#filter"
    = fa_icon "search", text: t(:filter)
#filter.collapse
  .well.well-small
    = search_form_for [@customer, @search], class: "form-horizontal" do |f|
      .form-group
        = f.label :name_cont, t(:name)+':', class: "col-sm-2 control-label"
        .col-sm-3
          = f.text_field :name_cont, class: 'search-field form-control'
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.button t(:search), class: 'btn btn-info btn-search'
          '
          button.btn.btn-info type="button" id="q_reset"
            =t(:reset)
table.table.table-striped
  thead
    tr
      th= sort_link @search, :id, t(:id)
      th= sort_link @search, :name, t(:name)
      th= t(:address)
      th= t(:photos)
      th=t(:actions)
  tbody
    - @offices.each do |office|
      tr
        td= office.id
        td= office.name
        td
          - if office.address
            = office.address.country.name + ', ' + office.address.state.name + ', ' + office.address.city.name + ', ' + office.address.street.name + ', ' + office.address.house.number.to_s + '/' + office.address.house.corps
        td
          = link_to customer_office_office_photos_path(@customer, office)
            = @photos_count[office.id] ? @photos_count[office.id] : '0'
        td
          = link_to customer_office_path(@customer, office), :class => 'btn btn-xs'
            = fa_icon "info-circle lg", title: t(:show)
          = link_to customer_office_contacts_path(@customer, office), class: "btn btn-xs"
            = fa_icon "list-alt lg", title: t(:contacts)
          = link_to edit_customer_office_path(@customer, office), :class => 'btn btn-xs'
            = fa_icon "edit lg", title: t(:edit)
          = link_to customer_office_path(@customer, office), :method => :delete, :data => { :confirm => t(:are_you_sure) }, :class => 'btn btn-xs'
            = fa_icon "remove", title: t(:remove)

=' link_to t(:new_office), new_customer_office_path, :class => 'btn btn-primary btn-new'

app/views/offices/new.html.slim
.page-header
  h1=t(:new_office)
= render :partial => "form"

app/views/offices/show.html.slim
-content_for :javascripts do
  = javascript_include_tag 'offices'
.page-header
  h1=t(:office)
.fieldset
  dl
    dt.label.label-default= t(:name)
    dd
      pre.prettyprint= @office.name
    dt.label.label-default= t(:desc)
    dd
      pre.prettyprint= @office.desc
    dt.label.label-default= t(:address)
    dd
      pre.prettyprint
        - if @office.address
          = @office.address.country.name + ', ' + @office.address.state.name + ', ' + @office.address.city.name + ', ' + @office.address.street.name + ', ' + @office.address.house.number.to_s + '/' + @office.address.house.corps
    dt.label.label-default= t(:categories)
    dd
      pre.prettyprint
        - @office.categories.each do |category|
          span.badge.alert-success
            = category.name

= link_to customer_office_contacts_path(@customer, @office)
  h4=t(:contacts)
p
  button.btn.btn-primary type="button" class="" data-toggle="collapse" data-target="#filter"
    = fa_icon "search", text: t(:filter)
#filter.collapse
  .well.well-small
    = search_form_for @search, :url => customer_office_path(@customer, @office), class: "form-horizontal" do |f|
      .form-group
        = f.label :actable_type_eq, t(:contact_type)+':', class: "col-sm-2 control-label"
        .col-sm-3
          = f.select :actable_type_eq, Contact::CONTACT_TYPES.map { |key, value| [value, key] }, {:include_blank => true}, {'data-placeholder' => t(:select_contact_type), :class => 'form-control'}
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.button t(:search), class: 'btn btn-info btn-search'
          '
          button.btn.btn-info type="button" id="q_reset"
            =t(:reset)
table.table.table-striped
  thead
    tr
      th= sort_link @search, :actable_type, t(:contact_type)
      th= t(:value)
      th= t(:actions)
  tbody
    - @contacts.each do |contact|
      - if contact.actable_type =='Phone'
        tr
          td= t contact.actable_type.downcase
          td
            = t Phone::PHONE_TYPES[contact.specific.phone_type]
            br
            = contact.specific.number
          td
            = link_to customer_office_phone_path(@customer, @office, contact.specific), class: "btn btn-xs"
              = fa_icon "info-circle lg"

            = link_to edit_customer_office_phone_path(@customer, @office, contact.specific), class: "btn btn-xs"
              = fa_icon "edit lg"

            = link_to customer_office_phone_path(@customer, @office, contact.specific), class: "btn btn-xs", :method => :delete, :data => { :confirm => t(:are_you_sure)}
              = fa_icon "remove"
      - elsif contact.actable_type =='Email'
        tr
          td= t contact.actable_type.downcase
          td
            = contact.specific.box
          td
            = link_to customer_office_email_path(@customer, @office, contact.specific), class: "btn btn-xs"
              = fa_icon "info-circle lg"

            = link_to edit_customer_office_email_path(@customer, @office, contact.specific), class: "btn btn-xs"
              = fa_icon "edit lg"

            = link_to customer_office_email_path(@customer, @office, contact.specific), class: "btn btn-xs", :method => :delete, :data => { :confirm => t(:are_you_sure)}
              = fa_icon "remove"
      - elsif contact.actable_type =='Site'
        tr
          td= t contact.actable_type.downcase
          td
            = link_to contact.specific.address, contact.specific.address
          td
            = link_to customer_office_site_path(@customer, @office, contact.specific), class: "btn btn-xs"
              = fa_icon "info-circle lg"

            = link_to edit_customer_office_site_path(@customer, @office, contact.specific), class: "btn btn-xs"
              = fa_icon "edit lg"

            = link_to customer_office_site_path(@customer, @office, contact.specific), class: "btn btn-xs", :method => :delete, :data => { :confirm => t(:are_you_sure)}
              = fa_icon "remove"
= paginate @contacts

.form-group
  = link_to t(:back), customer_offices_path(@customer), :class => 'btn btn-default btn-back'
  '
  = link_to t(:edit), edit_customer_office_path(@customer, @office), :class => 'btn btn-default btn-edit'
  '
  .btn-group
    button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
      =' t(:new_contact)
      span class="caret"
    ul class="dropdown-menu" role="menu"
      li
        = link_to t(:phone), new_customer_office_phone_path(@customer, @office)
      li
        = link_to t(:email), new_customer_office_email_path(@customer, @office)
      li
        = link_to t(:site), new_customer_office_site_path(@customer, @office)
  '
  - if @office.address
    =' link_to t(:edit_address), edit_customer_office_address_path(@customer, @office, @office.address), :class => 'btn btn-default btn-edit'
  - else
    =' link_to t(:new_address), new_customer_office_address_path(@customer, @office), :class => 'btn btn-default'
  = link_to t(:remove), customer_office_path(@customer, @office), :method => "delete", :data => { :confirm => t(:are_you_sure) }, :class => 'btn btn-danger btn-remove'