config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'private/uploads/:asset_type/:file', to: 'private_assets#show'

  root 'pages#index'
  resources :users do
    member do
      get :edit_password
      put :update_password
    end
  end
  resources :customers do
    resources :offices do
      resources :contacts, only: [:index]
      resources :phones
      resources :emails
      resources :sites
      resources :office_photos, path: 'photos'
      resources :addresses, except: [:index]
    end
  end
  resources :categories
  resources :countries do
    member do
      get :states
    end
  end
  resources :states do
    member do
      get :cities
    end
  end
  resources :cities do
    member do
      get :get_streets
    end
    resources :streets do
      member do
        get :get_houses
      end
      resources :houses
    end
    collection do
      get :states_in_country
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :lockable
  LANGUAGES = ['ru', 'en']
  validates :username, presence: true
  validates :username, :uniqueness => { :case_sensitive => false }
  validate :check_has_minimum_one_role
  validates :language, inclusion: { in: LANGUAGES, :message => I18n.t('errors.messages.blank')}
  has_and_belongs_to_many :roles
  has_many :customers, :dependent => :destroy


  def role?(role)
    return self.roles.find_by_name(role).try(:name) == role.to_s
  end

  def check_has_minimum_one_role
    if self.roles.empty?
      self.errors.add(:role, I18n.t('errors.messages.must_be_selected'))
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_password, :update_password]
  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @roles = Role.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @roles = Role.all

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: t(:user_created) }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @roles = Role.all

    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to users_path, notice: t(:user_updated) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /users/1/edit
  def edit
    @roles = Role.all
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_path, notice: t(:user_destroyed) }
      format.json { head :no_content }
    end
  end

  # GET /users
  # GET /users.json
  def index
    @roles = Role.all
    @search = User.search(params[:q])
    @users = @search.result.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end
  # GET /users/1
  # GET /users/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit_password
  def edit_password
  end

  # PUT /users/1/edit_password
  def update_password
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to users_path, notice: t(:password_updated) }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "edit_password" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :language, :role_ids)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
-if @user.errors.any?
  .alert.alert-danger
    button type="button" class="close" data-dismiss="alert"
      | &times;
    h4=t('errors.title')
    ul
    - @user.errors.full_messages.each do |msg|
      li= msg
= form_for @user, :html => { :class => "form-horizontal"} do |f|
  .form-group
    = f.label :username, t(:username)+':', class: "col-sm-2 control-label"
    .col-sm-3
      = f.text_field :username, class: 'form-control'
  .form-group
    = f.label :email, t(:email)+':', class: "col-sm-2 control-label"
    .col-sm-3
      = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :language, t(:language)+':', class: "col-sm-2 control-label"
    .col-sm-3
      = f.select(:language, {t(:russian) => 'ru', t(:english)=> 'en'}, {:include_blank => true}, {class: 'form-control', 'data-placeholder' => t(:select_language)})
  .form-group
    = f.label :role_ids, t(:role)+':', class: "col-sm-2 control-label"
    .col-sm-3
      = f.select :role_ids, @roles.collect  {|p| [ t(p.name), p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_role), :class => 'form-control'}
  .form-group
    = f.label :password, t(:password)+':', class: "col-sm-2 control-label"
    .col-sm-3
      = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, t(:password_confirmation)+':', class: "col-sm-2 control-label"
    .col-sm-3
      = f.password_field :password_confirmation, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      =' f.button t(:save), :class =>'btn btn-primary', :disable_with => t(:please_wait)
      = link_to t(:cancel), users_path, :class => 'btn btn-default'

app/views/users/edit.html.slim
-content_for :javascripts do
  = javascript_include_tag 'users'
.page-header
  h1= t(:edit_user)
-if @user.errors.any?
  .alert.alert-danger
    button type="button" class="close" data-dismiss="alert"
      | &times;
    h4=t('errors.title')
    ul
    - @user.errors.full_messages.each do |msg|
      li= msg
= form_for @user, :html => { :class => "form-horizontal"} do |f|
  .form-group
    = f.label :username, t(:username)+':', class: "col-sm-2 control-label"
    .col-sm-3
      = f.text_field :username, class: 'form-control'
  .form-group
    = f.label :email, t(:email)+':', class: "col-sm-2 control-label"
    .col-sm-3
      = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :language, t(:language)+':', class: "col-sm-2 control-label"
    .col-sm-3
      = f.select(:language, {t(:russian) => 'ru', t(:english)=> 'en'}, {:include_blank => true}, {class: 'form-control', 'data-placeholder' => t(:select_language)})
  .form-group
    = f.label :role_ids, t(:role)+':', class: "col-sm-2 control-label"
    .col-sm-3
      = f.select :role_ids, @roles.collect  {|p| [ t(p.name), p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_role), :class => 'form-control'}
  .form-group
    .col-sm-offset-2.col-sm-10
      =' f.button t(:save), :class =>'btn btn-primary', :disable_with => t(:please_wait)
      = link_to t(:cancel), users_path, :class => 'btn btn-default'

app/views/users/edit_password.html.slim
.page-header
  h1= t(:edit_password)
-if @user.errors.any?
  .alert.alert-danger
    button type="button" class="close" data-dismiss="alert"
      | &times;
    h4=t('errors.title')
    ul
    - @user.errors.full_messages.each do |msg|
      li= msg
= form_for @user, :url => update_password_user_path(@user), :method => :put, :html => { :class => "form-horizontal"} do |f|
  .form-group
    = f.label :password, t(:password)+':', class: "col-sm-2 control-label"
    .col-sm-3
      = f.password_field :password, class: 'col-sm-3 form-control'
  .form-group
    = f.label :password_confirmation, t(:password_confirmation)+':', class: "col-sm-2 control-label"
    .col-sm-3
      = f.password_field :password_confirmation, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.button t(:save), :class =>'btn btn-primary', :disable_with => t(:please_wait)
= link_to t(:back), users_path

app/views/users/index.html.slim
-content_for :javascripts do
  = javascript_include_tag 'users'
.page-header
  h1= t(:listing_users)
p
  button.btn.btn-primary type="button" class="" data-toggle="collapse" data-target="#filter"
    = fa_icon "search", text: t(:filter)
#filter.collapse
  .well.well-small
    = search_form_for @search, class: "form-horizontal" do |f|
      .form-group
        = f.label :username_cont, t(:username)+':', class: "col-sm-2 control-label"
        .col-sm-3
          = f.text_field :username_cont, class: 'search-field form-control'
      .form-group
        = f.label :email_cont, t(:email)+':', class: "col-sm-2 control-label"
        .col-sm-3
          = f.text_field :email_cont, class: 'search-field form-control'
      .form-group
        = f.label :roles_id_eq, t(:email)+':', class: "col-sm-2 control-label"
        .col-sm-3
          = f.select :roles_id_eq, @roles.collect  {|p| [ t(p.name), p.id ]}, {:include_blank => true},{'data-placeholder' => t(:select_role), :class => 'search-field form-control'}
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.button t(:search), class: 'btn btn-info btn-search'
          '
          button.btn.btn-info type="button" id="q_reset"
            =t(:reset)
table.table.table-striped.table-hover
  thead
    tr
      th
        = sort_link @search, :username, t(:username)
      th
        = sort_link @search, :email, t(:email)
      th
        = t(:roles)
      th
        =t(:actions)
  tbody
    - @users.each do |user|
      tr
        td= user.username
        td= user.email
        td
          -user.roles.each do |role|
            = t(role.name)
            br
        td
          = link_to user, class: "btn btn-xs"
            = fa_icon "info-circle lg"
          = link_to edit_user_path(user), class: "btn btn-xs"
            = fa_icon "edit lg"
          = link_to edit_password_user_path(user), class: "btn btn-xs"
            = fa_icon "lock lg"
          = link_to user, class: "btn btn-xs", method: :delete, data: { confirm: t(:are_you_sure)}
            = fa_icon "remove lg"
= paginate @users
p
  .page_entries_info
    = page_entries_info @users
= link_to t(:new_user), new_user_path, :class =>'btn btn-default btn-new', :disable_with => t(:please_wait)

app/views/users/new.html.slim
-content_for :javascripts do
  = javascript_include_tag 'users'
.page-header
  h1= t(:new_user)
== render 'form'

app/views/users/show.html.slim
.page-header
  h1=t(:user)
.fieldset
  dl
    dt.label.label-default= t(:username)
    dd
      pre.prettyprint= @user.username
    dt.label.label-default= t(:email)
    dd
      pre.prettyprint= @user.email
    dt.label.label-default= t(:language)
    dd
      pre.prettyprint= t(@user.language)
    dt.label.label-default= t(:roles)
    dd
      pre.prettyprint
        - @user.roles.each do |role|
          =' t(role.name)
.form-group
  =' link_to t(:back), users_path, :class => 'btn btn-default btn-back'
  =' link_to t(:edit), edit_user_path(@user), :class => 'btn btn-default btn-edit'
  = link_to t(:remove), user_path(@user), :method => "delete", :data => { :confirm => t(:are_you_sure) }, :class => 'btn btn-danger btn-remove'