config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'private/uploads/:asset_type/:file', to: 'private_assets#show'

  root 'pages#index'
  resources :users do
    member do
      get :edit_password
      put :update_password
    end
  end
  resources :customers do
    resources :offices do
      resources :contacts, only: [:index]
      resources :phones
      resources :emails
      resources :sites
      resources :office_photos, path: 'photos'
      resources :addresses, except: [:index]
    end
  end
  resources :categories
  resources :countries do
    member do
      get :states
    end
  end
  resources :states do
    member do
      get :cities
    end
  end
  resources :cities do
    member do
      get :get_streets
    end
    resources :streets do
      member do
        get :get_houses
      end
      resources :houses
    end
    collection do
      get :states_in_country
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :name, presence: true
  validates :name, :uniqueness => { :case_sensitive => false }
  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :offices, :dependent => :destroy
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  load_and_authorize_resource
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @search = Customer.search(params[:q])
    @customers = @search.result.page(params[:page])
    @offices_count = Office.group(:customer_id).count
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    @users = User.all
    @categories = Category.all
  end

  # GET /customers/1/edit
  def edit
    @users = User.all
    @categories = Category.all
  end

  # POST /customers
  # POST /customers.json
  def create
    @users = User.all
    @categories = Category.all
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: t(:customer_created) }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    @users = User.all
    @categories = Category.all
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: t(:customer_updated) }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: t(:customer_destroyed) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :desc, :user_id, :category_ids => [])
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.slim
-content_for :javascripts do
  = javascript_include_tag 'customers'
-if @customer.errors.any?
  .alert.alert-danger
    button type="button" class="close" data-dismiss="alert"
      | &times;
    h4=t('errors.title')
    ul
    - @customer.errors.full_messages.each do |msg|
      li= msg
= form_for @customer, :html => { :class => "form-horizontal" } do |f|
  .form-group
    = f.label :name, t(:name), :class => 'control-label col-md-2'
    .col-sm-3
      = f.text_field :name, :class => 'text_field form-control'
  .form-group
    = f.label :desc, t(:desc), :class => 'control-label col-md-2'
    .col-sm-3
      = f.text_area :desc, :class => 'text_field form-control', rows: 6
  .form-group
    = f.label :user_id, t(:user)+':', class: "col-sm-2 control-label"
    .col-sm-3
      = f.select :user_id, @users.collect  {|p| [ p.username, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_user), :class => 'form-control'}
  .form-group
    = f.label :category_ids, t(:categories)+':', class: "col-sm-2 control-label"
    .col-sm-3
      = f.select :category_ids, @categories.collect  {|p| [ p.name, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_categories), :multiple => true, :class => 'form-control'}
  .form-group
    .col-md-offset-2.col-sm-3
      =' f.button t(:save), :class =>'btn btn-primary', :disable_with => t(:please_wait)
      = link_to t(:cancel), customers_path, :class => 'btn btn-default'

app/views/customers/edit.html.slim
div class="page-header"
  h1=t(:edit_customer)
= render :partial => "form"

app/views/customers/index.html.slim
.page-header
  h1=t(:listing_customers)
p
  button.btn.btn-primary type="button" class="" data-toggle="collapse" data-target="#filter"
    = fa_icon "search", text: t(:filter)
#filter.collapse
  .well.well-small
    = search_form_for @search, class: "form-horizontal" do |f|
      .form-group
        = f.label :name_cont, t(:name)+':', class: "col-sm-2 control-label"
        .col-sm-3
          = f.text_field :name_cont, class: 'search-field form-control'
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.button t(:search), class: 'btn btn-info btn-search'
          '
          button.btn.btn-info type="button" id="q_reset"
            =t(:reset)
table.table.table-striped
  thead
    tr
      th= sort_link @search, :id, t(:id)
      th= sort_link @search, :name, t(:name)
      th= t(:offices)
      th= t(:actions)
  tbody
    - @customers.each do |customer|
      tr
        td= customer.id
        td= customer.name
        td
          = link_to customer_offices_path(customer)
            = @offices_count[customer.id] ? @offices_count[customer.id] : '0'
        td
          = link_to customer, class: "btn btn-xs"
            = fa_icon "info-circle lg", title: t(:show)

          = link_to edit_customer_path(customer), class: "btn btn-xs"
            = fa_icon "edit lg", title: t(:edit)

          = link_to customer, class: "btn btn-xs", :method => :delete, :data => { :confirm => t(:are_you_sure)}
            = fa_icon "remove", title: t(:remove)
= paginate @customers
p
  .page_entries_info
    = page_entries_info @customers
= link_to t(:new_customer), new_customer_path, :class => 'btn btn-default btn-new'

app/views/customers/new.html.slim
.page-header
  h1=t(:new_customer)
= render :partial => "form"

app/views/customers/show.html.slim
.page-header
  h1=t(:customer)

.fieldset
  dl
    dt.label.label-default= t(:name)
    dd
      pre.prettyprint= @customer.name
    dt.label.label-default= t(:desc)
    dd
      pre.prettyprint= @customer.desc
    dt.label.label-default= t(:user)
    dd
      pre.prettyprint= @customer.user ? @customer.user.username : t(:not_assigned)
    dt.label.label-default= t(:categories)
    dd
      pre.prettyprint
        - @customer.categories.each do |category|
          span.badge.alert-success
            = category.name


.form-group
  = link_to t(:back), customers_path, :class => 'btn btn-default btn-back'
  '
  = link_to t(:edit), edit_customer_path(@customer), :class => 'btn btn-default btn-edit'
  '
  = link_to t(:remove), customer_path(@customer), :method => "delete", :data => { :confirm => t(:are_you_sure) }, :class => 'btn btn-danger btn-remove'