config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'private/uploads/:asset_type/:file', to: 'private_assets#show'

  root 'pages#index'
  resources :users do
    member do
      get :edit_password
      put :update_password
    end
  end
  resources :customers do
    resources :offices do
      resources :contacts, only: [:index]
      resources :phones
      resources :emails
      resources :sites
      resources :office_photos, path: 'photos'
      resources :addresses, except: [:index]
    end
  end
  resources :categories
  resources :countries do
    member do
      get :states
    end
  end
  resources :states do
    member do
      get :cities
    end
  end
  resources :cities do
    member do
      get :get_streets
    end
    resources :streets do
      member do
        get :get_houses
      end
      resources :houses
    end
    collection do
      get :states_in_country
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/city.rb
class City < ActiveRecord::Base
  validates :name, :state, presence: true
  validates :name, :uniqueness => { :case_sensitive => false }
  belongs_to :state
  delegate :country, :to => :state, :allow_nil => true
  has_many :streets, :dependent => :destroy
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @search = City.search(params[:q])
    @cities = @search.result.page(params[:page])
    @streets_count = Street.group(:city_id).count
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cities }
    end
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
    @states = State.all
    @countries = Country.all
  end

  # GET /cities/1/edit
  def edit
    @states = State.all
    @countries = Country.all
    @select_country_id = @city.country.id
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)
    @states = State.all
    @countries = Country.all

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: t(:city_created) }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    @states = State.all
    @countries = Country.all
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: t(:city_updated) }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: t(:city_destroyed) }
      format.json { head :no_content }
    end
  end

  # GET /cities/1/get_streets
  def get_streets
    @streets = Street.where(city: params[:id])
    render :partial => "streets", :object => @streets
  end

  # GET /cities/states_in_country
  def states_in_country
    @states = State.where(country: params[:country_id])
    render :partial => "states", :object => @states
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :state_id)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.slim
-content_for :javascripts do
  = javascript_include_tag 'cities'
-if @city.errors.any?
  .alert.alert-danger
    button type="button" class="close" data-dismiss="alert"
      | &times;
    h4=t('errors.title')
    ul
    - @city.errors.full_messages.each do |msg|
      li= msg
= form_for @city, :html => { :class => "form-horizontal" } do |f|
  .form-group
    = f.label :name, t(:name), :class => 'control-label col-md-2'
    .col-sm-3
      = f.text_field :name, :class => 'text_field form-control'
  .form-group
    = f.label :country_id, t(:country), :class => 'control-label col-md-2'
    .col-sm-3
      = select_tag :country_id, options_for_select(@countries.collect {|p| [p.name ,p.id]}, @select_country_id), {:include_blank => true, 'data-placeholder' => t(:select_country), :class => 'form-control', :onchange => "update_states(this.value)"}
  .form-group#states
    - if @city.state
      = f.label t(:state), :class => 'control-label col-md-2'
      .col-sm-3
        = f.select :state_id, @states.collect  {|p| [ p.name, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_state), :class => 'form-control'}
  .form-group
    .col-md-offset-2.col-sm-3
      =' f.button t(:save), :class =>'btn btn-primary', :disable_with => t(:please_wait)
      = link_to t(:cancel), cities_path, :class => 'btn btn-default'

app/views/cities/_states.html.slim
= label_tag "city[state_id]", t(:state), class: "control-label col-md-2"
.col-sm-3
  = select_tag "city[state_id]", options_from_collection_for_select(@states, 'id', 'name') , {:include_blank => true, 'data-placeholder' => t(:select_state), :class => 'form-control'}

app/views/cities/_streets.html.slim
= label_tag "address[street_id]", t(:street), class: "control-label col-md-2"
.col-sm-3
  = select_tag "address[street_id]", options_from_collection_for_select(@streets, 'id', 'name') , {:include_blank => true, 'data-placeholder' => t(:select_street), :class => 'form-control', :onchange => 'onStreetChanged(this.value)'}

app/views/cities/edit.html.slim
.page-header
  h1=t(:edit_city)
= render :partial => "form"

app/views/cities/index.html.slim
.page-header
  h1=t(:listing_cities)
p
  button.btn.btn-primary type="button" class="" data-toggle="collapse" data-target="#filter"
    = fa_icon "search", text: t(:filter)
#filter.collapse
  .well.well-small
    = search_form_for @search, class: "form-horizontal" do |f|
      .form-group
        = f.label :name_cont, t(:name)+':', class: "col-sm-2 control-label"
        .col-sm-3
          = f.text_field :name_cont, class: 'search-field form-control'
      .form-group
        = f.label :state_country_name_cont, t(:country)+':', class: "col-sm-2 control-label"
        .col-sm-3
          = f.text_field :state_country_name_cont, class: 'search-field form-control'
      .form-group
        = f.label :state_name_cont, t(:state)+':', class: "col-sm-2 control-label"
        .col-sm-3
          = f.text_field :state_name_cont, class: 'search-field form-control'
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.button t(:search), class: 'btn btn-info btn-search'
          '
          button.btn.btn-info type="button" id="q_reset"
            =t(:reset)
table.table.table-striped
  thead
    tr
      th= sort_link @search, :id, t(:id)
      th= sort_link @search, :name, t(:name)
      th= sort_link @search, :country_name, t(:country)
      th= sort_link @search, :state_name, t(:state)
      th= t(:streets)
      th= t(:actions)
  tbody
    - @cities.each do |city|
      tr
        td= city.id
        td= city.name
        td= city.country.name
        td= city.state.name
        td
          = link_to city_streets_path(city)
            = @streets_count[city.id] ? @streets_count[city.id] : '0'
        td
          = link_to city, class: "btn btn-xs"
            = fa_icon "info-circle lg"

          = link_to edit_city_path(city), class: "btn btn-xs"
            = fa_icon "edit lg"

          = link_to city, class: "btn btn-xs", :method => :delete, :data => { :confirm => t(:are_you_sure)}
            = fa_icon "remove"

= paginate @cities
p
  .page_entries_info
    = page_entries_info @cities
= link_to t(:new_city), new_city_path, :class => 'btn btn-default btn-new'

app/views/cities/new.html.slim
.page-header
  h1=t(:new_city)
= render :partial => "form"

app/views/cities/show.html.slim
.page-header
  h1=t(:city)

.fieldset
  dl
    dt.label.label-default= t(:name)
    dd
      pre.prettyprint= @city.name
    dt.label.label-default= t(:country)
    dd
      pre.prettyprint= @city.country ? @city.country.name : t(:not)
    dt.label.label-default= t(:state)
    dd
      pre.prettyprint= @city.state ? @city.state.name : t(:not)

.form-group
  = link_to t(:back), cities_path, :class => 'btn btn-default btn-back'
  '
  = link_to t(:edit), edit_city_path(@city), :class => 'btn btn-default btn-edit'
  '
  = link_to t(:remove), city_path(@city), :method => "delete", :data => { :confirm => t(:are_you_sure) }, :class => 'btn btn-danger btn-remove'